# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-08-20 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmodel',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/static/images/logo.png'),
        ),
        migrations.AlterField(
            model_name='pphoto',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/static/images/logo.png'),
        ),
    ]
